### ISSUE TITLE
Dry run migration of production Hydrus content to H2 stage

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1063]
- [x] Request expansion of `sul-h2-stage:/data/h2-files` (`sf5-webapp-dev:/h2_test_vol`) mount from 80G to 5.6T: [DONE](https://github.com/sul-dlss/operations-tasks/issues/2481)
- [x] Request read-only mount of `sf5-webapp:/hydrus_files_prod` on sul-h2-stage at `/data/hydrus-files`: [DONE](https://github.com/sul-dlss/operations-tasks/issues/2481)
- [x] Rebase `migration` branch of Hydrus on `main` so that it may be safely deployed to prod for the export
- [x] Modify Hydrus exporter to only include collections and items belonging to collections in the [list of collections to be included in the migration (in column C)](https://docs.google.com/spreadsheets/d/1hNxM5hobMzrptxLctWfzDGSrl0ueBg5xGtQ47wFKC2g/edit#gid=0): [ATTACHED](https://github.com/sul-dlss/happy-heron/files/5999037/collection_druids.txt)
- [x] [Export collections](https://github.com/sul-dlss/hydrus/pull/507/files#diff-14e7df408fd5c4aef0b86331103bd44e56c2d000c10c535df59db6a9d5cd6982) on hydrus-prod: exported 125 collections with no errors
- [x] Transfer exported collection JSON from hydrus-prod to sul-h2-stage at `~/collections.jsonl`
- [x] [Export items](https://github.com/sul-dlss/hydrus/pull/507/files#diff-6c900ce23a9f4fd849fb84f5f983892e79ac44052b6d2421f08f84d74b97e12e) on hydrus-prod: exported 4,513 items with no errors
- [x] Transfer exported item JSON from hydrus-prod to sul-h2-stage at `~/items.jsonl`
- [x] Rebase `migrations2` branch of H2 on `main` so it may be deployed cleanly
  - [x] Make `bin/migrate-items` aware of the distinction between Works and WorkVersions
  - [x] [Modify H2 importer to implement migration of license data](https://github.com/sul-dlss/happy-heron/pull/777/files#diff-1cb52b410ad2b4a0ef195d88c77dd25e022bb0b9426fdbffaf9b384123b85f42R54-R58) for both items and collections
- [x] [Import collections](https://github.com/sul-dlss/happy-heron/pull/777/files) on sul-h2-stage: [RESULTS](https://github.com/sul-dlss/happy-heron/issues/1063#issuecomment-781635499)
- [x] [Import items and files](https://github.com/sul-dlss/happy-heron/pull/777/files) on sul-h2-stage: DONE

**Comment by jcoyne** [comment]
@amyehodge How does the collections to include in the dry run differ from what we eventually will migrate for production?

**Comment by amyehodge** [comment]
@jcoyne All of these collections (except for one intentional test collection we included) will be in the migration for production. But the dry run list may not yet all production collections in it.

**Comment by mjgiarlo** [comment]
# Collection druids to export (2021-02-17)

[collection_druids.txt](https://github.com/sul-dlss/happy-heron/files/5998650/collection_druids.txt)

**Comment by mjgiarlo** [comment]
# Item export errors on Hydrus prod

```
Error with druid:mw295sx0691. undefined method `roleMetadata' for #<Dor::Agreement:0x000000000a9d2d80>                                                
Error with druid:ds777pr3860. No such file or directory @ realpath_rec - /data/hydrus-files/ds/777/pr/3860/ds777pr3860
```

**Comment by mjgiarlo** [comment]
# Before collection migration stats

```
Users: 23                                                                                                                                             
Collections: 31                                                                                                                                       
ContactEmails: 38                                                                                                                                     
RelatedLinks: 0 
```

# After collection migration stats

```
Users: 804
Collections: 156
ContactEmails: 165
RelatedLinks: 123
```

**Comment by mjgiarlo** [comment]
# Before item migration stats

```
Users: 804
Authors: 8
Contributors: 0
ContactEmails: 166
Keywords: 7
RelatedLinks: 123
RelatedWorks: 0
Works: 9
WorkVersions: 9
AttachedFiles: 8
```

# After item migration stats

```
...
```

**Comment by jcoyne** [comment]
An error was encountered in druid:gb129dk1428 as it doesn't seem to have all its file on the hydrus mount (e.g. House_Election_Data_2012_v1.4.xlsx.zip), even though these are on stacks and preservation.

**Comment by jcoyne** [comment]
Another similar error was encountered on druid:xn020wg3781

```
No such file or directory @ rb_sysopen - /data/hydrus-files//xn/020/wg/3781/xn020wg3781/content/SDRPermission-IPCCSpecialReportonGlobalWarming.pdf (Errno::ENOENT)
```

**Comment by amyehodge** [comment]
That's odd -- I can't find that item in Hydrus or in Argo.

**Comment by mjgiarlo** [comment]
@jcoyne @amyehodge It'd be good to debrief on the dry-run today, perhaps after stand-up?

**Comment by mjgiarlo** [comment]
We're going to re-run the dry-run migration, and I'll create a new issue for it.

**Comment by mjgiarlo** [comment]
Superseded by https://github.com/sul-dlss/happy-heron/issues/1167
