### ISSUE TITLE
EPIC: Globus/file scalability/robustness

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3087]
Github wiki: https://github.com/sul-dlss/happy-heron/wiki/Large-Deposits

See #3114 for additional details

From Amy June 27, Requested limits (specifically to H2 and assuming usage of globus):
- 4 TB total object size
- 25k total number of files
- 4 TB total single file limit

**Current Limits:**

ZIP File:
- 25k total files works and tested to (not enforced, not shown to users, may work greater than 25k but slow)
- 10 GB single zip file (enforced as a single file, instructions shown to users)
- No actual enforced limit for total object size; may or may not work > 10 GB

Browser Upload:
- 250 total files (enforced)
- 10 GB single zip file (enforced as a single file, instructions shown to users)
- No actual enforced limit for total object size; may or may not work > 10 GB

Globus:
- 25k total files (Globus has a 100k limit for listing files from a directory: https://docs.globus.org/api/transfer/file_operations/#list_directory_contents)
- 4 TB total single file and total object size (provisioning of space done, Andrew setup to run a test).  Test successful #3270

Todo:
- [x] create ticket for language around total maximum number of files in an object (25k for ZIP and Globus) but no enforcement - #3267
- [x] create ticket to test 25k files via globus  - #3265
- [x] create ticket to test versioning of an object with 25k files (e.g. remove a file, add a new file) - #3266
- [x] check ticket to test 4 TB total object size via globus (may be already in progress or about to start via Andrew) - #3270
- [x] create ticket for language around total object size for Globus objects, 25k total files, 4 TB total object size - #3268

**Comment by amyehodge** [comment]
Closing as all related work documented here is complete.
