### ISSUE TITLE
Edit page

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#34]
- [ ] Form to enter metadata
  - ~~Sub-type (#88)~~
  - [x] License (#43)
  - [ ] Embargo date (#44)
  - [ ]  preferred citation (with generated citation?)(#45, #46)
  - [x] roles (author and creators) (#47)
  - [x] title (#48)
  - [x] Abstract (#50)
  - [x] Create date (#49)
- [ ] Attach files with progress bar (#51)
- [ ] Accessible
- [x] Save as draft button (#52 )
- [ ] Publish button (#40)
- [ ] Cancel button (#32 )

**Comment by jcoyne** [comment]
This has now been broken out into individual tickets so we don't need this uber-ticket..
